/*
 * Copyright (c) TIBCO Software Inc. 2005.
 * All Rights Reserved.
 */
package com.tibco.bw.unittest.runtime;

import com.tibco.neo.localized.BundleMessage;
import com.tibco.neo.localized.MessageBundle;

/**
 * A message bundle for this package.

 * THIS FILE WAS AUTOMATICALLY GENERATED BY A CONVERSION TOOL.
 * IF YOU EDIT IT, YOU MAY LOSE YOUR CHANGES.
 */
public class RuntimeMessageBundle extends MessageBundle {

    // Following member is accessed by MessageBundle.initializeMessages, do not remove!
    static public final String BUNDLE_NAME = "com.tibco.bw.unittest.runtime.Resources"; //$NON-NLS-1$

    static {
        MessageBundle.initializeMessages(RuntimeMessageBundle.class);
    }

    static public BundleMessage ACTIVITY_NOT_IN_TRANSACTION;
    static public BundleMessage ASSERT_NODE_EQUALS_PRIMITIVE_FAILURE_INEQUALITY;
    static public BundleMessage ASSERT_NODE_EQUALS_SUCCESFUL;
    
   
}
